### ISSUE TITLE
[Issue] Error Validating

### ISSUE THREAD

**Issue by tooraj-enayati** [bTayFla/PtTracker#11]
Occasionally PT-Tracker will stop working and will display the following message. I have to kill mongoose in Task Manager and restart PT-Tracker to recover from it.

![36292552-9b769b16-1326-11e8-897a-b2996c265083](https://user-images.githubusercontent.com/24386973/36333884-a13d5a38-13cd-11e8-81f5-030d0b5171ae.JPG)

**Comment by juanmalic** [comment]
Hi,

Same issue here: 
![captura de pantalla 2018-02-16 a las 19 23 48](https://user-images.githubusercontent.com/36056235/36322795-f50fb176-134e-11e8-8bfc-f5f18896e597.png)

**Comment by jwyatt1787** [comment]
me too! What's happening?

**Comment by blindaim** [comment]
A buddy and I pooled our money for Profit Tracker and decided to buy one license of Profit Tracker instead of using the shared Google Sheet to track the bot performance. At $100 it seemed kind of high, but seemed like a good project. If they are going to nickle and dime us to where we have to buy two separate licenses for the same Profit Trailer bot, I'm not going to give very favorable reviews anytime I hear people ask about the product. Not happy whatsoever. So here we are, I can check it and then have to close the browser so my friend can wait 5 minutes and try again. Seriously????

**Comment by blindaim** [comment]
@tooraj-enayati  You should obfuscate your IP

**Comment by tooraj-enayati** [comment]
@blindaim, Done. Thanks! I wasn't thinking.

**Comment by tooraj-enayati** [comment]
@blindaim, it is a bug. I have it running on two instances. But after a while, it gets its knickers in a twist and I have to kill mongoose and restart both instances.

**Comment by blindaim** [comment]
Developer is very responsive. I jump to conclusions too fast sometimes :)

**Comment by clownfish44** [comment]
Set your IP here http://pttracker.net/license/changeIP/

**Comment by tooraj-enayati** [comment]
@clownfish44 

http://pttracker.net/license/changeIP/ broke my PT-Tracker!  I am sure I enter all the details correctly!

I now can't even start PT-Tracker on my VPS! I get:

"There's an error in your configuration. Please check your PtTracker.json file."
