### ISSUE TITLE
[Feature Request] Use weighed average

### ISSUE THREAD

**Issue by elitriona** [bTayFla/PtTracker#13]
For the average profit %, wouldn't it make more sense to show it as a WEIGHTED average instead of a simple average? If I make .01 BTC one day, and then .1 BTC another day, that is a massive difference. Taking into account the weighted average might be helpful when showing the average profit %.

**Comment by Tornado-Truxton** [comment]
Imagine that you invest 100,000 USDT and earn 1,000 USDT in the first 30 days. Your account is now worth 101,000 USDT. Your earnings percentage is equal to 1%, which is calculated by dividing the earnings, 1,000, by the net amount invested, 100,000.
 
Now, imagine that on the last day of the month you withdraw 90,000 to put a downpayment on a Lambo. Your net total investment is now 10,000 (100,000 - 90,000), but your balance is 11,000. By the simple earnings percentage calculation, your return is now 1,000 divided by 10,000, or 10%. This number does not accurately reflect your actual returns.    
 
In these cases, your actual earnings percentage is better represented by dividing the amount earned by your average invested amount over the time period. Because you had about 100,000 for most of that month, except the last day when it was 10,000, your average invested is 97,000.  So your earnings percentage in this case is 1,000 / 97,000 = 1.03%. While this adjusted percentage isn’t a perfect reflection of reality either, it does tend to be much more representative of your actual return than the distorted 10% number.
