### ISSUE TITLE
Import of data 

### ISSUE THREAD

**Issue by BlitzKC** [bTayFla/PtTracker#21]
I left a request earlier similar.

The issue was closed with no explanation?  I do you have a better way to request?

**Comment by clownfish44** [comment]
The request earlier was closed I did go back and comment on it with"Closed because we are not going to implement this anytime soon as this is strictly for PT right now." as you wanted this to pull from other exchanges and old data. As time goes on we will be implementing a way to pull from api for bittrex, binance and polonex but for now this request will be closed. Thank you for you suggestions :D

**Comment by d4260** [comment]
If this isn't to be done.
How about resolving PTTracker corrupting the Profit Trailer log?
