### ISSUE TITLE
pending orders value missing from daily sales

### ISSUE THREAD

**Issue by SyedIsTesting** [bTayFla/PtTracker#24]
Any orders in pending log once sold are missing from the daily sales figures.

Can this be fixed asap as this is causing a lot of headache with checking back at the exchange to verify whats happened with any particular pair.

**Comment by LGSONE** [comment]
Noticed this as well.  Manual buys will show up obviously but if you take that same pair and put a manual limit or stop limit on it and it is executed no data in sales log and PT Tracker does not show the transaction from the DB.  using .19 PT.  Pulling data for manual trades ...

**Comment by woodyalien** [comment]
Guys, I don't think this is PTT issue, but in fact PT itself. Have in mind that PTT reads PT's data so, once PT does not record a sale from "pending log", PTT cannot see it.

The question is in fact: should PT track "pending log" sales? By concept PT tracks what PT does, it sums the bot's profit and not your own human performance in parallel to the bot - so having a PendingLog sale (one you have manually created) moved to SalesLog is discussable and not primarily an issue to PT nor PTT because of the concepts behind them.

* BUT I just said "PT tracks what PT does": I can tell you that PT fails there sometimes - sometimes PT creates orders as "pending" (not me!), not anymore trailing nor DCAing, just sitting there, and those sales are not going to SalesLog neither - this is real failure because PT had all actions and failed to track them... and so PTT "fails" as consequence.

Anyway I think you should bring this topic to PT's github.

**Comment by LGSONE** [comment]
Got it, thanks.  Manual and created pending orders in Pt should be part of the sales log.  IIRC the data is there but unless it is sold via the bot it is not there.  needs to be or I hear from Another that PTT will do this soon...  All these apps in 6 months are going to be nicely tuned..

**Comment by clownfish44** [comment]
Both of these are PT issues and will not be fixed as confirmed by the dev of PT. However, we may try to do some sort of API call to see your orders history.
