### ISSUE TITLE
[Bug] Time on browser is going off UTC time for profit days etc

### ISSUE THREAD

**Issue by razorseal** [bTayFla/PtTracker#61]
Multiple people just started reporting it on discord now. Aqua advised us it uses the pt time offset off PT, but most people's "next day" just started when UTC went into next day.

you can see in the picture attached that PT shows correct time at 8:57 PM on 3/13 (shown bottom right on screenshot) but PTT shows march 14th for date. It's using the UTC time to calcuate profit days etc I think.

**Comment by oiler2112** [comment]
Confirmed, mine is doing this as well.

**Comment by razorseal** [comment]
I noticed when you make a sale, it still shows on correct date for daily profits; However the dashboard's today's profit becomes the next day on UTC. So it will show 0% for profit at say 10 pm, and any sale made will go on yesterday's profit.

**Comment by smoochy** [comment]
I do also have a time related bug.

I am living in Germany and have set `server.timeZoneOffset = +01:00` in PT application.properties.
In my PT sales log the time is correct and I do get the Telegram push notifications at the correct time.

Last night short before 1am local time, I was lying in bed, getting notifications about sales. But they did not show up on PTT.

I am talking about the SUBETH sale here, which happened at 0:55am local time:

![img_0206](https://user-images.githubusercontent.com/34371932/37507186-932706d0-28ed-11e8-8b44-01e1656bc9b4.jpg)

As you can see from the next screenshot, it is not being seen at all by PTT, even 4 minutes later. And it was not counted towards the 15th of March. Looking right now at the amount of sales on 15th of March, it is sill 11:

![img_0205](https://user-images.githubusercontent.com/34371932/37507286-063ff6d6-28ee-11e8-9dc8-6911f40ff049.PNG)

After 1am local time, the sale showed up in PTT, but the time was off. Not by 1 hour, but other amounts of minutes:

![img_0207](https://user-images.githubusercontent.com/34371932/37507610-b27571dc-28ef-11e8-936f-760394bbcedf.jpg)


I never really paid attention to the time before, I can not say, if this issue was already present in V2.0 or even in V1.13.

Running Ubuntu 16.04. Update to 2.0.1 last night around 10pm. I already stopped PTT, deleted the pttracker.db and let it recreate. It now has a different size (160KB compared to the original file of 172KB), but all times are still off.

Let me know if you need more information from me to narrow down the cause.

**Comment by razorseal** [comment]
The problem is gone for me in v 2.0.1

**Comment by clownfish44** [comment]
Issue solved in 2.0.1
