### ISSUE TITLE
March 26th

### ISSUE THREAD

**Issue by samirsayz** [bTayFla/PtTracker#96]
The software is not showing any sales for March 26th. It is now 2:14 AM, but the new day has not started yet.

**Comment by propergol** [comment]
I had same issue but not exactly : 
Inside PT's application.properties : server.timeZoneOffset = +02:00
Inside Ptracker
- sales are correctly listing with correct time
- but dashboard didnt show march 26 line until UTC midnight, so 2AM here

**Comment by propergol** [comment]
Well, in my case the issue is only the "Daily Profit" on Dashboard that only starts displaying current day in UTC time and so in my case is late by 2 hours.

But when the line is displayed then the amount in %  is correct.

**Comment by smoochy** [comment]
What a coincidence that on 25th of March there was a reset of clocks. https://en.wikipedia.org/wiki/Summer_Time_in_Europe

I need to set `server.timeZoneOffset = +02:00` now in PT application.properties file to have the correct time as I am living in Germany. Germany during wintertime is UTC +1. Now, during Summer Time, it is UTC +2. This results in no current sales showing up until 2am in PTT.

**Comment by monte-crypto** [comment]
Yeah clearly many people are facing the same issue. My day starts perfectly on Profit Trailer dashboard. The problem I'm facing is only on PtTracker. My UTC time is set properly in the application.properties for Profit Trailer which is why I have no issues in there.

What is the solution to have the day restart exactly at 12 am on PtTracker? Is there a solution yet?

**Comment by monte-crypto** [comment]
Yeah clearly many people are facing the same issue. My day starts perfectly on Profit Trailer dashboard. The problem I'm facing is only on PtTracker. My UTC time is set properly in the application.properties for Profit Trailer which is why I have no issues in there.

What is the solution to have the day restart exactly at 12 am on PtTracker? Is there a solution yet? It is currently 12:40 am March 27th, and now the previous two days are not showing! See the image:

![capture](https://user-images.githubusercontent.com/36898337/37927341-6ddb3d20-3157-11e8-9702-694c66cda4f8.JPG)

**Comment by Zombato** [comment]
I have no trades displayed since March 26, though there are plenty of them in PT

**Comment by Zombato** [comment]
10 days and still no answer from the devs...

**Comment by LiamAird** [comment]
We can be found in our Discord group, where we offer support. 
These issues are for collecting issues, not for supporting.

**Comment by clownfish44** [comment]
Origional guy's pt password was wrong!

**Comment by monte-crypto** [comment]
Why have you guys closed this?? There's no solution yet!

**Comment by LiamAird** [comment]
Join the discord for help: https://discord.gg/Er6UfJm
We do not offer supper through these issues. We use them as collection
